name: Firmware

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -Dclippy::all

      - name: Run tests
        run: cargo test


      - name: Check formatting
        run: cargo fmt --check
